version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: rappdw/docker-java-python
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/pip-project

    steps:
      - checkout
      - run: 
          name: install dependencies
          command: |
            python2.7 -m pip install -r requirements.txt
            pip freeze
            bash <(curl -s https://scripts.scantist.com/staging/ci-circle-jar.sh)

